sudo: false
language: go
go:
- 1.6.3
- 1.7
before_install:
  - "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
env:
  global:
    - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
    - TEST=small
install:
  - cd $SNAP_PLUGIN_SOURCE
  - make deps
script:
  - make check 2>&1 # Run test suite